-- Table of common chemical compounds and their formulae
-- (all of these parse correctly)

INSERT INTO compounds(compound, formula) VALUES
  ('Glucose'                         ,'C₆H₁₂O₆'),
  ('Fluoride'                        ,'F⁻'),
  ('Bromide'                         ,'Br⁻'),
  ('Arsenite'                        ,'AsO₃³⁻'),
  ('Nitrate'                         ,'NO₃⁻'),
  ('Sulfite'                         ,'SO₃₂²⁻'),
  ('Bromate'                         ,'BrO₃⁻'),
  ('Carbonate'                       ,'CO₃²⁻'),
  ('Acetate'                         ,'CH₃COO⁻'),
  ('Cyanate'                         ,'OCN⁻'),
  ('Hydroxide'                       ,'OH⁻'),
  ('Lithium Hydrogen Sulfate'        ,'LiHSO₄'),
  ('Lithium Hydrogen Carbonate'      ,'LiHCO₃'),
  ('Lithium Perchlorate'             ,'LiClO₄'),
  ('Lithium Acetate'                 ,'LiC₂H₃O₂'),
  ('Lithium Sulfate'                 ,'Li₂SO₄'),
  ('Lithium Dichromate'              ,'Li₂Cr₂O₇'),
  ('Lithium Nitride'                 ,'Li₃N'),
  ('Lithium Sulfide'                 ,'Li₂S'),
  ('Lithium Chloride'                ,'LiCl'),
  ('Sodium Nitrate'                  ,'NaNO₃'),
  ('Sodium Permanganate'             ,'NaMnO₄'),
  ('Sodium Chlorate'                 ,'NaClO₃'),
  ('Sodium Periodate'                ,'NaIO₄'),
  ('Sodium Sulfite'                  ,'Na₂SO₃'),
  ('Sodium Chromate'                 ,'Na₂CrO₄'),
  ('Sodium Arsenate'                 ,'Na₃AsO₄'),
  ('Sodium Oxide'                    ,'Na₂O'),
  ('Sodium Fluoride'                 ,'NaF'),
  ('Potassium Nitrite'               ,'KNO₂'),
  ('Potassium Cyanide'               ,'KCN'),
  ('Potassium Chlorite'              ,'KClO₂'),
  ('Potassium Iodate'                ,'KIO₃'),
  ('Potassium Carbonate'             ,'K₂CO₃'),
  ('Potassium Peroxide'              ,'K₂O₂'),
  ('Potassium Phosphate'             ,'K₃PO₄'),
  ('Potassium Arsenide'              ,'K₃As'),
  ('Potassium Telluride'             ,'K₂Te'),
  ('Potassium Iodide'                ,'KI'),
  ('Rubidium Hydroxide'              ,'RbOH'),
  ('Rubidium Hypochlorite'           ,'RbClO'),
  ('Rubidium Bromate'                ,'RbBrO₃'),
  ('Rubidium Dihydrogen Phosphate'   ,'RbH₂PO₄'),
  ('Rubidium Thiosulfate'            ,'Rb₂S₂O₃'),
  ('Rubidium Hydrogen Phosphate'     ,'Rb₂HPO₄'),
  ('Rubidium Phosphide'              ,'Rb₃P'),
  ('Rubidium Selenide'               ,'Rb₂Se'),
  ('Rubidium Bromide'                ,'RbBr'),
  ('Cesium Hydrogen Sulfate'         ,'CsHSO₄'),
  ('Cesium Hydrogen Carbonate'       ,'CsHCO₃'),
  ('Cesium Perchlorate'              ,'CsClO₄'),
  ('Cesium Acetate'                  ,'CsC₂H₃O₂'),
  ('Cesium Sulfate'                  ,'Cs₂SO₄'),
  ('Cesium Dichromate'               ,'Cs₂Cr₂O₇'),
  ('Cesium Nitride'                  ,'Cs₃N'),
  ('Cesium Sulfide'                  ,'Cs₂S'),
  ('Cesium Chloride'                 ,'CsCl'),
  ('Beryllium Sulfite'               ,'BeSO₃'),
  ('Beryllium Chromate'              ,'BeCrO₄'),
  ('Beryllium Phosphide'             ,'Be₃P₂'),
  ('Beryllium Selenide'              ,'BeSe'),
  ('Beryllium Bromide'               ,'BeBr₂'),
  ('Magnesium Sulfate'               ,'MgSO₄'),
  ('Magnesium Dichromate'            ,'MgCr₂O₇'),
  ('Magnesium Arsenide'              ,'Mg₃As₂'),
  ('Magnesium Telluride'             ,'MgTe'),
  ('Magnesium Iodide'                ,'MgI₂'),
  ('Calcium Thiosulfate'             ,'CaS₂O₃'),
  ('Calcium Hydrogen Phosphate'      ,'CaHPO₄'),
  ('Calcium Oxide'                   ,'CaO'),
  ('Calcium Fluoride'                ,'CaF₂'),
  ('Strontium Carbonate'             ,'SrCO₃'),
  ('Strontium Peroxide'              ,'SrO₂'),
  ('Strontium Nitride'               ,'Sr₃N₂'),
  ('Strontium Sulfide'               ,'SrS'),
  ('Strontium Chloride'              ,'SrCl₂'),
  ('Barium Sulfite'                  ,'BaSO₃'),
  ('Barium Chromate'                 ,'BaCrO₄'),
  ('Barium Phosphide'                ,'Ba₃P₂'),
  ('Barium Selenide'                 ,'BaSe'),
  ('Barium Bromide'                  ,'BaBr₂'),
  ('Scandium Nitride'                ,'ScN'),
  ('Scandium Sulfide'                ,'Sc₂S₃'),
  ('Scandium Chloride'               ,'ScCl₃'),
  ('Yttrium Arsenate'                ,'YAsO₄'),
  ('Yttrium Oxide'                   ,'Y₂O₃'),
  ('Yttrium Fluoride'                ,'YF₃'),
  ('Lanthanum Phosphate'             ,'LaPO₄'),
  ('Lanthanum Arsenide'              ,'LaAs'),
  ('Lanthanum Telluride'             ,'La₂Te₃'),
  ('Lanthanum Iodide'                ,'LaI₃'),
  ('Titanium II Thiosulfate'         ,'TiS₂O₃'),
  ('Titanium II Hydrogen Phosphate'  ,'TiHPO₄'),
  ('Titanium II Oxide'               ,'TiO'),
  ('Titanium II Fluoride'            ,'TiF₂'),
  ('Titanium III Phosphate'          ,'TiPO₄'),
  ('Titanium III Arsenide'           ,'TiAs'),
  ('Titanium III Telluride'          ,'Ti₂Te₃'),
  ('Titanium III Iodide'             ,'TiI₃'),
  ('Vanadium II Thiosulfate'         ,'VS₂O₃'),
  ('Vanadium II Hydrogen Phosphate'  ,'VHPO₄'),
  ('Vanadium II Oxide'               ,'VO'),
  ('Vanadium II Fluoride'            ,'VF₂'),
  ('Vanadium III Phosphate'          ,'VPO₄'),
  ('Vanadium III Arsenide'           ,'VAs'),
  ('Vanadium III Telluride'          ,'V₂Te₃'),
  ('Vanadium III Iodide'             ,'VI₃'),
  ('Chromium II Thiosulfate'         ,'CrS₂O₃'),
  ('Chromium II Hydrogen Phosphate'  ,'CrHPO₄'),
  ('Chromium II Oxide'               ,'CrO'),
  ('Chromium II Fluoride'            ,'CrF₂'),
  ('Chromium III Phosphate'          ,'CrPO₄'),
  ('Chromium III Arsenide'           ,'CrAs'),
  ('Chromium III Telluride'          ,'Cr₂Te₃'),
  ('Chromium III Iodide'             ,'CrI₃'),
  ('Manganese II Thiosulfate'        ,'MnS₂O₃'),
  ('Manganese II Hydrogen Phosphate' ,'MnHPO₄'),
  ('Manganese II Oxide'              ,'MnO'),
  ('Manganese II Fluoride'           ,'MnF₂'),
  ('Manganese III Phosphate'         ,'MnPO₄'),
  ('Manganese III Arsenide'          ,'MnAs'),
  ('Manganese III Telluride'         ,'Mn₂Te₃'),
  ('Manganese III Iodide'            ,'MnI₃'),
  ('Technetium II Thiosulfate'       ,'TcS₂O₃'),
  ('Technetium II Hydrogen Phosphate','TcHPO₄'),
  ('Technetium II Oxide'             ,'TcO'),
  ('Technetium II Fluoride'          ,'TcF₂'),
  ('Iron II Carbonate'               ,'FeCO₃'),
  ('Iron II Peroxide'                ,'FeO₂'),
  ('Iron II Nitride'                 ,'Fe₃N₂'),
  ('Iron II Sulfide'                 ,'FeS'),
  ('Iron II Chloride'                ,'FeCl₂'),
  ('Iron III Arsenate'               ,'FeAsO₄'),
  ('Iron III Oxide'                  ,'Fe₂O₃'),
  ('Iron III Fluoride'               ,'FeF₃'),
  ('Cobalt II Carbonate'             ,'CoCO₃'),
  ('Cobalt II Peroxide'              ,'CoO₂'),
  ('Cobalt II Nitride'               ,'Co₃N₂'),
  ('Cobalt II Sulfide'               ,'CoS'),
  ('Cobalt II Chloride'              ,'CoCl₂'),
  ('Cobalt III Arsenate'             ,'CoAsO₄'),
  ('Cobalt III Oxide'                ,'Co₂O₃'),
  ('Cobalt III Fluoride'             ,'CoF₃'),
  ('Nickel II Carbonate'             ,'NiCO₃'),
  ('Nickel II Peroxide'              ,'NiO₂'),
  ('Nickel II Nitride'               ,'Ni₃N₂'),
  ('Nickel II Sulfide'               ,'NiS'),
  ('Nickel II Chloride'              ,'NiCl₂'),
  ('Palladium II Sulfite'            ,'PdSO₃'),
  ('Palladium II Chromate'           ,'PdCrO₄'),
  ('Palladium II Phosphide'          ,'Pd₃P₂'),
  ('Palladium II Selenide'           ,'PdSe'),
  ('Palladium II Bromide'            ,'PdBr₂'),
  ('Platinum II Sulfate'             ,'PtSO₄'),
  ('Platinum II Dichromate'          ,'PtCr₂O₇'),
  ('Platinum II Arsenide'            ,'Pt₃As₂'),
  ('Platinum II Telluride'           ,'PtTe'),
  ('Platinum II Iodide'              ,'PtI₂'),
  ('Platinum IV Oxide'               ,'PtO₂'),
  ('Platinum IV Fluoride'            ,'PtF₄'),
  ('Copper I Nitrite'                ,'CuNO₂'),
  ('Copper I Cyanide'                ,'CuCN'),
  ('Copper I Chlorite'               ,'CuClO₂'),
  ('Copper I Iodate'                 ,'CuIO₃'),
  ('Copper I Carbonate'              ,'Cu₂CO₃'),
  ('Copper I Peroxide'               ,'Cu₂O₂'),
  ('Copper I Phosphate'              ,'Cu₃PO₄'),
  ('Copper I Arsenide'               ,'Cu₃As'),
  ('Copper I Telluride'              ,'Cu₂Te'),
  ('Copper I Iodide'                 ,'CuI'),
  ('Copper II Thiosulfate'           ,'CuS₂O₃'),
  ('Copper II Hydrogen Phosphate'    ,'CuHPO₄'),
  ('Copper II Oxide'                 ,'CuO'),
  ('Copper II Fluoride'              ,'CuF₂'),
  ('Silver Nitrite'                  ,'AgNO₂'),
  ('Silver Cyanide'                  ,'AgCN'),
  ('Silver Chlorite'                 ,'AgClO₂'),
  ('Silver Iodate'                   ,'AgIO₃'),
  ('Silver Carbonate'                ,'Ag₂CO₃'),
  ('Silver Peroxide'                 ,'Ag₂O₂'),
  ('Silver Phosphate'                ,'Ag₃PO₄'),
  ('Silver Arsenide'                 ,'Ag₃As'),
  ('Silver Telluride'                ,'Ag₂Te'),
  ('Silver Iodide'                   ,'AgI'),
  ('Gold I Hydroxide'                ,'AuOH'),
  ('Gold I Hypochlorite'             ,'AuClO'),
  ('Gold I Bromate'                  ,'AuBrO₃'),
  ('Gold I Dihydrogen Phosphate'     ,'AuH₂PO₄'),
  ('Gold I Thiosulfate'              ,'Au₂S₂O₃'),
  ('Gold I Hydrogen Phosphate'       ,'Au₂HPO₄'),
  ('Gold I Phosphide'                ,'Au₃P'),
  ('Gold I Selenide'                 ,'Au₂Se'),
  ('Gold I Bromide'                  ,'AuBr'),
  ('Gold III Nitride'                ,'AuN'),
  ('Gold III Sulfide'                ,'Au₂S₃'),
  ('Gold III Chloride'               ,'AuCl₃'),
  ('Zinc Sulfite'                    ,'ZnSO₃'),
  ('Zinc Chromate'                   ,'ZnCrO₄'),
  ('Zinc Phosphide'                  ,'Zn₃P₂'),
  ('Zinc Selenide'                   ,'ZnSe'),
  ('Zinc Bromide'                    ,'ZnBr₂'),
  ('Cadmium Sulfate'                 ,'CdSO₄'),
  ('Cadmium Dichromate'              ,'CdCr₂O₇'),
  ('Cadmium Arsenide'                ,'Cd₃As₂'),
  ('Cadmium Telluride'               ,'CdTe'),
  ('Cadmium Iodide'                  ,'CdI₂'),
  ('Mercury I Thiosulfate'           ,'Hg₂S₂O₃'),
  ('Mercury I Hydrogen Phosphate'    ,'Hg₂HPO₄'),
  ('Mercury I Telluride'             ,'Hg₂Te'),
  ('Mercury I Iodide'                ,'Hg₂I₂'),
  ('Mercury II Thiosulfate'          ,'HgS₂O₃'),
  ('Mercury II Hydrogen Phosphate'   ,'HgHPO₄'),
  ('Mercury II Oxide'                ,'HgO'),
  ('Mercury II Fluoride'             ,'HgF₂'),
  ('Aluminum Phosphate'              ,'AlPO₄'),
  ('Aluminum Arsenide'               ,'AlAs'),
  ('Aluminum Telluride'              ,'Al₂Te₃'),
  ('Aluminum Iodide'                 ,'AlI₃'),
  ('Gallium II Thiosulfate'          ,'GaS₂O₃'),
  ('Gallium II Hydrogen Phosphate'   ,'GaHPO₄'),
  ('Gallium II Oxide'                ,'GaO'),
  ('Gallium II Fluoride'             ,'GaF₂'),
  ('Gallium III Phosphate'           ,'GaPO₄'),
  ('Gallium III Arsenide'            ,'GaAs'),
  ('Gallium III Telluride'           ,'Ga₂Te₃'),
  ('Gallium III Iodide'              ,'GaI₃'),
  ('Indium I Hydroxide'              ,'InOH'),
  ('Indium I Hypochlorite'           ,'InClO'),
  ('Indium I Bromate'                ,'InBrO₃'),
  ('Indium I Dihydrogen Phosphate'   ,'InH₂PO₄'),
  ('Indium I Thiosulfate'            ,'In₂S₂O₃'),
  ('Indium I Hydrogen Phosphate'     ,'In₂HPO₄'),
  ('Indium I Phosphide'              ,'In₃P'),
  ('Indium I Selenide'               ,'In₂Se'),
  ('Indium I Bromide'                ,'InBr'),
  ('Indium II Sulfate'               ,'InSO₄'),
  ('Indium II Dichromate'            ,'InCr₂O₇'),
  ('Indium II Arsenide'              ,'In₃As₂'),
  ('Indium II Telluride'             ,'InTe'),
  ('Indium II Iodide'                ,'InI₂'),
  ('Indium III Phosphide'            ,'InP'),
  ('Indium III Selenide'             ,'In₂Se₃'),
  ('Indium III Bromide'              ,'InBr₃'),
  ('Thallium I Hydrogen Sulfate'     ,'TlHSO₄'),
  ('Thallium I Hydrogen Carbonate'   ,'TlHCO₃'),
  ('Thallium I Perchlorate'          ,'TlClO₄'),
  ('Thallium I Acetate'              ,'TlC₂H₃O₂'),
  ('Thallium I Sulfate'              ,'Tl₂SO₄'),
  ('Thallium I Dichromate'           ,'Tl₂Cr₂O₇'),
  ('Thallium I Nitride'              ,'Tl₃N'),
  ('Thallium I Sulfide'              ,'Tl₂S'),
  ('Thallium I Chloride'             ,'TlCl'),
  ('Thallium III Arsenate'           ,'TlAsO₄'),
  ('Thallium III Oxide'              ,'Tl₂O₃'),
  ('Thallium III Fluoride'           ,'TlF₃'),
  ('Tin II Carbonate'                ,'SnCO₃'),
  ('Tin II Peroxide'                 ,'SnO₂'),
  ('Tin II Nitride'                  ,'Sn₃N₂'),
  ('Tin II Sulfide'                  ,'SnS'),
  ('Tin II Chloride'                 ,'SnCl₂'),
  ('Tin IV Phosphide'                ,'Sn₃P₄'),
  ('Tin IV Selenide'                 ,'SnSe₂'),
  ('Tin IV Bromide'                  ,'SnBr₄'),
  ('Lead II Sulfate'                 ,'PbSO₄'),
  ('Lead II Dichromate'              ,'PbCr₂O₇'),
  ('Lead II Arsenide'                ,'Pb₃As₂'),
  ('Lead II Telluride'               ,'PbTe'),
  ('Lead II Iodide'                  ,'PbI₂'),
  ('Lead IV Oxide'                   ,'PbO₂'),
  ('Lead IV Fluoride'                ,'PbF₄'),
  ('Ammonium Nitrite'                ,'NH₄NO₂'),
  ('Ammonium Cyanide'                ,'NH₄CN'),
  ('Ammonium Chlorite'               ,'NH₄ClO₂'),
  ('Ammonium Iodate'                 ,'NH₄IO₃'),
  ('Ammonium Fluoride'               ,'NH₄F'),
  ('Ammonium'                        ,'NH₄⁺'),
  ('Gold'                            ,'Au⁺'),
  ('Rubidium'                        ,'Rb⁺'),
  ('Cadmium'                         ,'Cd²⁺'),
  ('Lead'                            ,'Pb²⁺'),
  ('Uranyl'                          ,'UO₂²⁺'),
  ('Cobalt'                          ,'Co³⁺'),
  ('Silicon'                         ,'Si⁴⁺'),
  ('Bismuth'                         ,'Bi⁵⁺');
